import sys
import json
from fpdf import FPDF
from datetime import datetime

class ChampionshipReport(FPDF):
    def header(self):
        # Dark background for header
        self.set_fill_color(10, 10, 12)
        self.rect(0, 0, 210, 40, 'F')
        
        # Logo text
        self.set_font('Arial', 'B', 24)
        self.set_text_color(0, 255, 136) # #00ff88
        self.cell(0, 20, 'ZIROWORK', 0, 1, 'L')
        
        self.set_font('Arial', 'B', 12)
        self.set_text_color(212, 212, 212) # #d4d4d4
        self.cell(0, 0, 'CHAMPIONSHIP-LEVEL PROGRESS MIRROR', 0, 1, 'L')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(112, 112, 120) # #707078
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Ziro Senior Operator Ecosystem', 0, 0, 'C')

def generate_pdf(data, output_path):
    pdf = ChampionshipReport()
    pdf.add_page()
    
    student = data.get('student', {})
    student_name = f"{student.get('first_name', '')} {student.get('last_name', '')}".strip() or "Student"
    kpis = data.get('kpis', {})
    goals = data.get('goals', [])
    
    # Student Info Section
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 10, f"Student: {student_name}", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 5, f"Instrument: {student.get('instrument', 'N/A')}", 0, 1)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%B %d, %Y')}", 0, 1)
    pdf.ln(10)
    
    # KPI Grid
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "CHAMPIONSHIP METRICS", 0, 1, 'L')
    
    col_width = 45
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(col_width, 10, "Goals Completed", 1, 0, 'C', True)
    pdf.cell(col_width, 10, "Skills Mastered", 1, 0, 'C', True)
    pdf.cell(col_width, 10, "Checkpoints Passed", 1, 0, 'C', True)
    pdf.cell(col_width, 10, "Evidence Items", 1, 1, 'C', True)
    
    pdf.set_font('Arial', '', 12)
    pdf.cell(col_width, 15, f"{kpis.get('goalsCompleted', 0)}/{kpis.get('totalGoals', 0)}", 1, 0, 'C')
    pdf.cell(col_width, 15, f"{kpis.get('skillsMastered', 0)}/{kpis.get('totalSkills', 0)}", 1, 0, 'C')
    pdf.cell(col_width, 15, f"{kpis.get('checkpointsPassed', 0)}/{kpis.get('totalCheckpoints', 0)}", 1, 0, 'C')
    pdf.cell(col_width, 15, f"{kpis.get('evidenceCount', 0)}", 1, 1, 'C')
    pdf.ln(10)
    
    # Goals & Skills
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "DETAILED PROGRESS", 0, 1)
    
    for goal in goals:
        pdf.set_font('Arial', 'B', 11)
        pdf.set_fill_color(230, 255, 240)
        pdf.cell(0, 8, f"Goal: {goal.get('title', 'Untitled Goal')}", 0, 1, 'L', True)
        
        for skill in goal.get('skills', []):
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(60, 60, 60)
            status = " [MASTERED]" if skill.get('is_mastered') else ""
            pdf.cell(10) # Indent
            pdf.cell(0, 7, f"- {skill.get('title', 'Untitled Skill')}{status}", 0, 1)
            
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(100, 100, 100)
            for cp in skill.get('checkpoints', []):
                cp_status = "X" if cp.get('is_passed') else " "
                pdf.cell(20) # Indent
                pdf.cell(0, 5, f"[{cp_status}] {cp.get('title', 'Untitled Checkpoint')}", 0, 1)
        pdf.ln(5)

    pdf.output(output_path)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_report_pdf.py <json_data_path> <output_pdf_path>")
        sys.exit(1)
        
    data_path = sys.argv[1]
    output_path = sys.argv[2]
    
    with open(data_path, 'r') as f:
        data = json.load(f)
        
    generate_pdf(data, output_path)
    print(f"Successfully generated PDF at {output_path}")
